kind: pipeline
name: Packer_Build

steps:
  - name: Packer - Validate
    image: hashicorp/packer
    commands:
      - packer validate -var-file=default.json packer.json
  - name: Packer - Build
    image: hashicorp/packer
    commands:
      - packer build -var aws_access_key='${aws_access_key}' -var aws_secret_key='${aws_secret_key}' -var-file=default.json packer.json
  - name: Packer - Build
    environment:
      aws_access_key:
        from_secret: aws_access_key
      aws_secret_key:
        from_secret: aws_secret_key
      aws_subnet_id:
        from_secret: aws_subnet_id
      aws_vpc_id:
        from_secret: aws_vpc_id