kind: pipeline
name: default

steps:
  - name: Packer
    image: appleboy/drone-packer
    template: packer.json
    vars_files:
      - default.json
    secret_variables: [ aws_access_key, aws_secret_key, aws_subnet_id, aws_vpc_id]
    secrets: [ aws_access_key, aws_secret_key, aws_subnet_id, aws_vpc_id]
    actions:
      - validate