kind: pipeline
name: default

steps:
  - name: Packer
    image: hashicorp/packer
    commands:
      - packer validate -var-file=default.json packer.json
      - packer build -var-file=default.json packer.json
    secret_variables: [ aws_access_key, aws_secret_key, aws_subnet_id, aws_vpc_id]
    secrets: [ aws_access_key, aws_secret_key, aws_subnet_id, aws_vpc_id]